name: a2data_task1

services:
  nginx:
    image: nginx:1.31.3-alpine

    container_name: a2data_task1_nginx

    ports:
      - "${NGINX_HOST_PORT}:${NGINX_PORT}"

    depends_on:
      app:
        condition: service_healthy

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - frontend

  app:
    build:
      context: .

    expose:
    - "8000"

    depends_on:
      redis:
        condition: service_healthy

    env_file:
      - .env

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=2)",
        ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - frontend
      - backend

  redis:
    image: redis:8.8.1-alpine

    container_name: a2data_task1_redis

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s

    volumes:
      - redis-data:/data

    networks:
      - backend

networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge
    internal: true

volumes:
  redis-data: